##
## EPITECH PROJECT, 2020
## fozz
## File description:
## bazz
##

NAME = fozzbazz

FILES = fozzbazz.c

all :	$(NAME)

$(NAME):
	gcc -o $(NAME) $(FILES)

clean:
	rm -f *.o

fclean:	clean
	rm -f $(NAME)

re:	fclean all
