##
## EPITECH PROJECT, 2020
## make
## File description:
## make
##

NAME = 104intersection 

FILES = intersection.c

all :	$(NAME)

$(NAME):
	gcc -o $(NAME) $(FILES) -lm

clean:
	rm -f *.o

fclean:	clean
	rm -f $(NAME)

re:	fclean all
