##
## EPITECH PROJECT, 2020
## fuzz
## File description:
## bozz
##

NAME = fuzzbozz

FILES = fuzzbozz.c

all :	$(NAME)

$(NAME):
	gcc -o $(NAME) $(FILES)

clean:
	rm -f *.o

fclean:	clean
	rm -f $(NAME)

re:	fclean all
